import type { Alcance } from './matriz.js'

/**
 * A matriz de permissão escrita de novo, à mão, célula a célula: papel, recurso, ação e alcance. O teste compara
 * as duas nos dois sentidos, e mudar uma célula da `MATRIZ` sem mudar a linha daqui deixa a esteira vermelha
 * (RF17). Não gere este arquivo a partir da matriz: a cópia à mão é o que obriga a mudança a ser olhada duas vezes.
 */
export const EXPECTATIVA_DA_MATRIZ: ReadonlyArray<readonly [papel: string, recurso: string, acao: string, alcance: Alcance]> = [
  // rede: só agregado, e só do indicador de professor (regra 10, item 8; regra 70, item 8)
  ['rede', 'sistema_contexto', 'ler', 'nunca'],
  ['rede', 'sistema_job_sintetico', 'criar', 'nunca'],
  ['rede', 'sistema_job_sintetico', 'ler', 'nunca'],
  ['rede', 'eu', 'ler', 'nunca'],
  ['rede', 'sessao', 'registrar_atividade', 'nunca'],
  ['rede', 'sessao', 'encerrar', 'nunca'],
  ['rede', 'sessao', 'trocar_escola', 'nunca'],
  ['rede', 'escola_configuracao', 'alterar', 'nunca'],
  ['rede', 'ano_letivo', 'ler', 'nunca'],
  ['rede', 'ano_letivo', 'criar', 'nunca'],
  ['rede', 'ano_letivo', 'abrir', 'nunca'],
  ['rede', 'ano_letivo', 'encerrar', 'nunca'],
  ['rede', 'serie', 'ler', 'nunca'],
  ['rede', 'serie', 'criar', 'nunca'],
  ['rede', 'disciplina', 'ler', 'nunca'],
  ['rede', 'disciplina', 'criar', 'nunca'],
  ['rede', 'disciplina', 'renomear', 'nunca'],
  ['rede', 'disciplina', 'excluir', 'nunca'],
  ['rede', 'turma', 'ler', 'nunca'],
  ['rede', 'turma', 'listar', 'nunca'],
  ['rede', 'turma', 'criar', 'nunca'],
  ['rede', 'turma', 'renomear', 'nunca'],
  ['rede', 'turma', 'excluir', 'nunca'],
  ['rede', 'aluno_da_turma', 'ler', 'nunca'],
  ['rede', 'vinculo', 'ler', 'nunca'],
  ['rede', 'vinculo', 'criar', 'nunca'],
  ['rede', 'vinculo', 'encerrar', 'nunca'],
  ['rede', 'vinculo', 'ler_proprios', 'nunca'],
  ['rede', 'vinculo', 'confirmar', 'nunca'],
  ['rede', 'vinculo', 'contestar', 'nunca'],
  ['rede', 'usuario_mfa', 'redefinir', 'nunca'],
  ['rede', 'indicador_professor', 'ler_agregado', 'agregado'],
  ['rede', 'indicador_professor', 'ler_nominal', 'nunca'],

  // coordenador: a unidade; aluno e indicador nominal só com auditoria
  ['coordenador', 'sistema_contexto', 'ler', 'proprio'],
  ['coordenador', 'sistema_job_sintetico', 'criar', 'unidade'],
  ['coordenador', 'sistema_job_sintetico', 'ler', 'unidade'],
  ['coordenador', 'eu', 'ler', 'proprio'],
  ['coordenador', 'sessao', 'registrar_atividade', 'proprio'],
  ['coordenador', 'sessao', 'encerrar', 'proprio'],
  ['coordenador', 'sessao', 'trocar_escola', 'proprio'],
  ['coordenador', 'escola_configuracao', 'alterar', 'unidade'],
  ['coordenador', 'ano_letivo', 'ler', 'unidade'],
  ['coordenador', 'ano_letivo', 'criar', 'unidade'],
  ['coordenador', 'ano_letivo', 'abrir', 'unidade'],
  ['coordenador', 'ano_letivo', 'encerrar', 'unidade'],
  ['coordenador', 'serie', 'ler', 'unidade'],
  ['coordenador', 'serie', 'criar', 'unidade'],
  ['coordenador', 'disciplina', 'ler', 'unidade'],
  ['coordenador', 'disciplina', 'criar', 'unidade'],
  ['coordenador', 'disciplina', 'renomear', 'unidade'],
  ['coordenador', 'disciplina', 'excluir', 'unidade'],
  ['coordenador', 'turma', 'ler', 'unidade'],
  ['coordenador', 'turma', 'listar', 'unidade'],
  ['coordenador', 'turma', 'criar', 'unidade'],
  ['coordenador', 'turma', 'renomear', 'unidade'],
  ['coordenador', 'turma', 'excluir', 'unidade'],
  ['coordenador', 'aluno_da_turma', 'ler', 'nominal_auditado'],
  ['coordenador', 'vinculo', 'ler', 'unidade'],
  ['coordenador', 'vinculo', 'criar', 'unidade'],
  ['coordenador', 'vinculo', 'encerrar', 'unidade'],
  ['coordenador', 'vinculo', 'ler_proprios', 'nunca'],
  ['coordenador', 'vinculo', 'confirmar', 'nunca'],
  ['coordenador', 'vinculo', 'contestar', 'nunca'],
  ['coordenador', 'usuario_mfa', 'redefinir', 'unidade'],
  ['coordenador', 'indicador_professor', 'ler_agregado', 'agregado'],
  ['coordenador', 'indicador_professor', 'ler_nominal', 'nominal_auditado'],

  // professor: as turmas dele e o próprio vínculo e indicador
  ['professor', 'sistema_contexto', 'ler', 'proprio'],
  ['professor', 'sistema_job_sintetico', 'criar', 'unidade'],
  ['professor', 'sistema_job_sintetico', 'ler', 'unidade'],
  ['professor', 'eu', 'ler', 'proprio'],
  ['professor', 'sessao', 'registrar_atividade', 'proprio'],
  ['professor', 'sessao', 'encerrar', 'proprio'],
  ['professor', 'sessao', 'trocar_escola', 'proprio'],
  ['professor', 'escola_configuracao', 'alterar', 'nunca'],
  ['professor', 'ano_letivo', 'ler', 'nunca'],
  ['professor', 'ano_letivo', 'criar', 'nunca'],
  ['professor', 'ano_letivo', 'abrir', 'nunca'],
  ['professor', 'ano_letivo', 'encerrar', 'nunca'],
  ['professor', 'serie', 'ler', 'nunca'],
  ['professor', 'serie', 'criar', 'nunca'],
  ['professor', 'disciplina', 'ler', 'nunca'],
  ['professor', 'disciplina', 'criar', 'nunca'],
  ['professor', 'disciplina', 'renomear', 'nunca'],
  ['professor', 'disciplina', 'excluir', 'nunca'],
  ['professor', 'turma', 'ler', 'turma_vinculada'],
  ['professor', 'turma', 'listar', 'nunca'],
  ['professor', 'turma', 'criar', 'nunca'],
  ['professor', 'turma', 'renomear', 'nunca'],
  ['professor', 'turma', 'excluir', 'nunca'],
  ['professor', 'aluno_da_turma', 'ler', 'turma_vinculada'],
  ['professor', 'vinculo', 'ler', 'nunca'],
  ['professor', 'vinculo', 'criar', 'nunca'],
  ['professor', 'vinculo', 'encerrar', 'nunca'],
  ['professor', 'vinculo', 'ler_proprios', 'proprio'],
  ['professor', 'vinculo', 'confirmar', 'proprio'],
  ['professor', 'vinculo', 'contestar', 'proprio'],
  ['professor', 'usuario_mfa', 'redefinir', 'nunca'],
  ['professor', 'indicador_professor', 'ler_agregado', 'nunca'],
  ['professor', 'indicador_professor', 'ler_nominal', 'proprio'],

  // aluno: a si mesmo
  ['aluno', 'sistema_contexto', 'ler', 'proprio'],
  ['aluno', 'sistema_job_sintetico', 'criar', 'nunca'],
  ['aluno', 'sistema_job_sintetico', 'ler', 'nunca'],
  ['aluno', 'eu', 'ler', 'proprio'],
  ['aluno', 'sessao', 'registrar_atividade', 'proprio'],
  ['aluno', 'sessao', 'encerrar', 'proprio'],
  ['aluno', 'sessao', 'trocar_escola', 'nunca'],
  ['aluno', 'escola_configuracao', 'alterar', 'nunca'],
  ['aluno', 'ano_letivo', 'ler', 'nunca'],
  ['aluno', 'ano_letivo', 'criar', 'nunca'],
  ['aluno', 'ano_letivo', 'abrir', 'nunca'],
  ['aluno', 'ano_letivo', 'encerrar', 'nunca'],
  ['aluno', 'serie', 'ler', 'nunca'],
  ['aluno', 'serie', 'criar', 'nunca'],
  ['aluno', 'disciplina', 'ler', 'nunca'],
  ['aluno', 'disciplina', 'criar', 'nunca'],
  ['aluno', 'disciplina', 'renomear', 'nunca'],
  ['aluno', 'disciplina', 'excluir', 'nunca'],
  ['aluno', 'turma', 'ler', 'nunca'],
  ['aluno', 'turma', 'listar', 'nunca'],
  ['aluno', 'turma', 'criar', 'nunca'],
  ['aluno', 'turma', 'renomear', 'nunca'],
  ['aluno', 'turma', 'excluir', 'nunca'],
  ['aluno', 'aluno_da_turma', 'ler', 'nunca'],
  ['aluno', 'vinculo', 'ler', 'nunca'],
  ['aluno', 'vinculo', 'criar', 'nunca'],
  ['aluno', 'vinculo', 'encerrar', 'nunca'],
  ['aluno', 'vinculo', 'ler_proprios', 'nunca'],
  ['aluno', 'vinculo', 'confirmar', 'nunca'],
  ['aluno', 'vinculo', 'contestar', 'nunca'],
  ['aluno', 'usuario_mfa', 'redefinir', 'nunca'],
  ['aluno', 'indicador_professor', 'ler_agregado', 'nunca'],
  ['aluno', 'indicador_professor', 'ler_nominal', 'nunca'],
]
